services:
  app:
    image: 058264194030.dkr.ecr.us-east-2.amazonaws.com/laravel-lab-planner:latest
    restart: unless-stopped
    ports:
      - "9000:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - FILESYSTEM_DISK=local
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=pgsql
      - DB_HOST=${DB_HOST}
      - DB_PORT=5432
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/up"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - planner
networks:
  planner:
    external: true
